### ISSUE TITLE
Image compression enabled for prod but testmysite.withgoogle.com cannot detect image compression

### ISSUE THREAD

**Issue by oninross** [sindresorhus/gulp-imagemin#264]
As title says, I have `gulp --production` with image compression for pngs and jpgs.  I have deployed to a Firebase hosting but when I run my site at testmysite.withgoogle.com, it says "Optimise Images"

![screenshot_052217_100038_am](https://cloud.githubusercontent.com/assets/2233813/26288644/b732374c-3ed9-11e7-9355-db075b7ba1fc.jpg)

**Comment by kevva** [comment]
What does this plugin output when you're running gulp? You should get a message with how many files and how much their file size were reduced.

**Comment by oninross** [comment]
The plugin is not throwing any errors.  I enabled verbose to see if it's actually compressing and it is.

Jpeg compression is just true or false right? How to lower the options further?

**Comment by kevva** [comment]
You can set options by doing this https://github.com/sindresorhus/gulp-imagemin#custom-plugin-options.

I closed it because it doesn't sound like it's an issue with this module since you aren't getting any errors or any other input that tells us otherwise.

**Comment by oninross** [comment]
The issue is that the images after compression still fails Google's page insight.

**Comment by kevva** [comment]
Yes, but that can happen due to a number of reasons. Your images might be really large to begin with and needs to minified further etc. However, it's not a bug.

**Comment by markadrake** [comment]
We need more details, but obviously the plugin for imagemin should be optimizing them to the same standard Google is. It sounds like @oninross isn't able to achieve that. I found this issue because I have a similar experience with my website. The lossless compression from jpegtran (?) I guess isn't as well optimized as whatever Google expects. There could be many factors at play here, but could we put together a test or come to the conclusion it's an issue with say - jpegtran vs imagemin vs gulp-imagemin?
