### ISSUE TITLE
spawn ENOENT

### ISSUE THREAD

**Issue by zzswang** [sindresorhus/gulp-imagemin#54]
version  ^0.6.0

It seems imagemin have some problems on its dependencies.

**Comment by xobs** [comment]
I ran into this problem in 3.2.0, when building a Docker image.  I kept coming to this ticket, which is why I'm posting the solution here.

My Dockerfile looks like this:

    FROM node:7.9.0
    COPY . /app
    WORKDIR /app
    RUN npm install --global gulp-cli
    RUN npm install
    RUN gulp build

When I run "gulp build", I get the following error:

    events.js:163
          throw er; // Unhandled 'error' event
          ^
    Error: spawn /app/node_modules/gifsicle/vendor/gifsicle ENOENT
        at exports._errnoException (util.js:1050:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
        at onErrorNT (internal/child_process.js:367:16)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickCallback (internal/process/next_tick.js:104:9)

The problem was caused by the COPY including my node_modules directory from the host.  It didn't reinstall gulp-imagemin because it assumed it was already installed.

The solution was to create a .dockerignore file that contained "node_modules".  That way, npm would rebuild gulp-imagemin, and everything worked as expected.
